import { test, expect } from '@playwright/test';

test('six-stage simulator works through the real Python bridge', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('#main')).toBeVisible({ timeout: 120_000 });
  await expect(page.locator('#target-out')).not.toBeEmpty();
  await page.locator('#tabs [data-tab="firing"]').click();
  await expect(page.locator('#btn-simulate')).toBeDisabled();
  await page.locator('#tabs [data-tab="search"]').click();
  await page.locator('#btn-propose').click();
  await expect(page.locator('[data-adopt="0"]')).toBeVisible();
  await page.locator('[data-inspect="0"]').click();
  await expect(page.locator('[data-inspect-out="0"]')).not.toBeEmpty();
  await page.locator('[data-adopt="0"]').click();
  await page.locator('#tabs [data-tab="glazing"]').click();
  await page.locator('#btn-density').click();
  await expect(page.locator('#density-out')).not.toBeEmpty();
  await page.locator('#btn-dip').click();
  await expect(page.locator('#dip-out')).not.toBeEmpty();
  await page.locator('#btn-ware').click();
  await expect(page.locator('#ware-out')).not.toBeEmpty();
  await page.locator('#btn-glaze').click();
  await expect(page.locator('#glaze-out')).not.toBeEmpty();
  await page.locator('#tabs [data-tab="risk"]').click();
  await page.locator('#btn-risk').click();
  await expect(page.locator('#risk-out')).not.toBeEmpty();
  await page.locator('#tabs [data-tab="firing"]').click();
  await page.locator('#btn-loading').click();
  await page.locator('#btn-cooling').click();
  await expect(page.locator('#cooling-out')).not.toBeEmpty();
  await page.locator('#e-control-sim input[type="number"]').fill('300');
  await expect(page.locator('#btn-simulate')).toBeEnabled();
  await page.locator('#btn-simulate').click();
  await expect(page.locator('#sim-out')).toContainText('가정');
  await page.locator('#btn-record-run').click();
  await page.locator('#tabs [data-tab="record"]').click();
  await page.locator('#btn-result').click();
  await expect(page.locator('#result-out')).toContainText('목표까지 거리');
  expect(errors).toEqual([]);
});
